apiVersion: v2
name: cert-manager-config
description: A Helm chart for cert-manager ClusterIssuers and configuration
type: application
version: 0.1.0
appVersion: "v1.13.0"
home: https://cert-manager.io
sources:
  - https://github.com/cert-manager/cert-manager
keywords:
  - cert-manager
  - certificates
  - tls
  - ssl
  - letsencrypt
  - cloudflare
maintainers:
  - name: Your Name
    email: your.email@example.com