{{- if and .Values.cloudflare.enabled (not .Values.cloudflare.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cloudflare.secretName | default "cloudflare-api-token-secret" }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cert-manager-config.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.cloudflare.apiToken }}
  api-token: {{ .Values.cloudflare.apiToken | b64enc | quote }}
  {{- end }}
  {{- if .Values.cloudflare.apiKey }}
  api-key: {{ .Values.cloudflare.apiKey | b64enc | quote }}
  {{- end }}
{{- end }}
---
{{- if not .Values.cloudflare.existingSecret }}
# NOTE: This is a template for Cloudflare API secrets. In production:
# 1. Use external secret management (External Secrets Operator, Vault, etc.)
# 2. Or provide secrets via --set-file or separate secret files
# 3. Never commit actual API tokens to Git repositories
#
# Example usage with API Token (recommended):
# helm install cert-manager-config ./cert-manager-config \
#   --set cloudflare.apiToken="your-cloudflare-api-token"
#
# Example usage with API Key (legacy):
# helm install cert-manager-config ./cert-manager-config \
#   --set cloudflare.apiKey="your-cloudflare-api-key"
#
# Or use existing secret:
# helm install cert-manager-config ./cert-manager-config \
#   --set cloudflare.existingSecret="my-cloudflare-secret"
{{- end }}
